
server.port=5000


    spring.datasource.url=jdbc:mysql://farmeraid.cz8i0ugwsf73.us-east-2.rds.amazonaws.com:3306/cloud
    spring.datasource.username=admin
    spring.datasource.password=tarakkhurana

    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=kisaanconnect_secret_key_kisaanconnect_secret_key
jwt.expiration=86400000
